export const FETCH_NEAREST_FLIGHTS = "FETCH_NEAREST_FLIGHTS";
export const FETCH_NEAREST_FLIGHTS_SUCCES = "FETCH_NEAREST_FLIGHTS_SUCCES";
export const FETCH_NEAREST_FLIGHTS_FAILURE = "FETCH_NEAREST_FLIGHTS_FAILURE";
export const RESET_NEAREST_FLIGHTS = "RESET_NEAREST_FLIGHTS";
